name: Go Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat-**'

env:
  EACHMODULE_CONCURRENCY: 2
  SMITHY_GO_REPOSITORY: ${{ github.event.pull_request.head.repo.owner.login }}/smithy-go
  GIT_PAT: ${{ secrets.CI_GIT_PAT}}

jobs:
  unix-tests:
    name: Unix SDK tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ["1.20", "1.21", "1.22"]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Find smithy-go
      env:
        RUNNER_TMPDIR: ${{ runner.temp }}
      run: ./ci-find-smithy-go.sh

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Test
      run: make ci-test-no-generate

  windows-tests:
    name: Windows SDK Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        go-version: ["1.20", "1.21", "1.22"]
    env:
      EACHMODULE_SKIP: "internal\\repotools\\changes"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Find smithy-go
      shell: bash
      env:
        RUNNER_TMPDIR: ${{ runner.temp }}
      run: ./ci-find-smithy-go.sh

    - name: Test
      run: make vet build unit-test
